"""
Alert system configuration policy.

"""

import datetime
import os
from horey.configuration_policy.configuration_policy import ConfigurationPolicy

# pylint: disable=missing-function-docstring


class AlertSystemConfigurationPolicy(ConfigurationPolicy):
    """
    Main class.

    """

    ALERT_SYSTEM_CONFIGURATION_FILE_PATH = "alert_system_configuration.json"
    ALERT_SYSTEM_SELF_MONITORING_LOG_ERROR_FILTER_PATTERN = "[ERROR]"
    ALERT_SYSTEM_SELF_MONITORING_LOG_TIMEOUT_FILTER_PATTERN = "Task timed out after"
    # These key and value are added in the message dict to indicate the received message is self monitoring
    ALERT_SYSTEM_SELF_MONITORING_TYPE_KEY = "ALERT_SYSTEM_SELF_MONITORING"
    ALERT_SYSTEM_SELF_MONITORING_TYPE_VALUE = "ALERT_SYSTEM_SELF_MONITORING"

    def __init__(self):
        super().__init__()
        self._deployment_datetime = None
        self._horey_repo_path = None
        self._lambda_name = None
        self._sns_topic_name = None
        self._region = None
        self._notification_channels = None
        self._message_classes = None
        self._active_deployment_validation = False
        self._lambda_role_name = None
        self._lambda_role_path = None
        self._tags = None
        self._routing_tags = None
        self._ses_configuration_set_name = None
        self._dynamodb_table_name = None
        self._do_not_send_ses_suppressed_bounce_notifications = False

    @property
    def do_not_send_ses_suppressed_bounce_notifications(self):
        return self._do_not_send_ses_suppressed_bounce_notifications

    @do_not_send_ses_suppressed_bounce_notifications.setter
    def do_not_send_ses_suppressed_bounce_notifications(self, value):
        self._do_not_send_ses_suppressed_bounce_notifications = value

    @property
    def deployment_datetime(self):
        if self._deployment_datetime is None:
            self._deployment_datetime = datetime.datetime.now().strftime(
                "%Y_%m_%d_%H_%M_%S"
            )
        return self._deployment_datetime

    @deployment_datetime.setter
    def deployment_datetime(self, value):
        self._deployment_datetime = value
        # raise self.StaticValueError("deployment_datetime is autogenerated")

    @property
    def deployment_directory_path(self):
        return f"/tmp/alert_system/{self.deployment_datetime}"

    @property
    def deployment_venv_path(self):
        return os.path.join(self.deployment_directory_path, "_venv")

    @property
    def lambda_zip_file_name(self):
        return "lambda_function.zip"

    @property
    def horey_repo_path(self):
        if self._horey_repo_path is None:
            raise self.UndefinedValueError("horey_repo_path")
        return self._horey_repo_path

    @horey_repo_path.setter
    def horey_repo_path(self, value):
        self._horey_repo_path = value

    @property
    def region(self):
        if self._region is None:
            raise self.UndefinedValueError("region")

        return self._region

    @region.setter
    def region(self, value):
        self._region = value

    @property
    def sns_topic_name(self):
        if self._sns_topic_name is None:
            self._sns_topic_name = "alert_system_generic"
        return self._sns_topic_name

    @sns_topic_name.setter
    def sns_topic_name(self, value):
        self._sns_topic_name = value

    @property
    def lambda_name(self):
        if self._lambda_name is None:
            raise ValueError("Lambda name was not set.")

        return self._lambda_name

    @lambda_name.setter
    def lambda_name(self, value):
        self._lambda_name = value

    @property
    def lambda_role_name(self):
        if self._lambda_role_name is None:
            self._lambda_role_name = "role-lambda-alert_system"
        return self._lambda_role_name

    @lambda_role_name.setter
    def lambda_role_name(self, value):
        self._lambda_role_name = value

    @property
    def lambda_role_path(self):
        if self._lambda_role_path is None:
            self._lambda_role_path = "role-lambda-alert_system"
        return self._lambda_role_path

    @lambda_role_path.setter
    def lambda_role_path(self, value):
        self._lambda_role_path = value

    @property
    def subscription_name(self):
        return "alert_system_generic_subscription"

    @property
    def lambda_timeout(self):
        return 30

    @property
    def notification_channels(self):
        return self._notification_channels

    @notification_channels.setter
    def notification_channels(self, value):
        self._notification_channels = value

    @property
    def message_classes(self):
        return self._message_classes

    @message_classes.setter
    def message_classes(self, value):
        self._message_classes = value

    @property
    def active_deployment_validation(self):
        return self._active_deployment_validation

    @active_deployment_validation.setter
    def active_deployment_validation(self, value):
        self._active_deployment_validation = value

    @property
    def alert_system_lambda_log_group_name(self):
        return f"/aws/lambda/{self.lambda_name}"

    @property
    def ses_configuration_set_name(self):
        if self._ses_configuration_set_name is None:
            self._ses_configuration_set_name = "conf_set_alert_system_default"

        return self._ses_configuration_set_name

    @ses_configuration_set_name.setter
    def ses_configuration_set_name(self, value):
        self._ses_configuration_set_name = value

    @property
    def tags(self):
        if self._tags is None:
            raise self.UndefinedValueError("tags")

        return self._tags

    @tags.setter
    def tags(self, value):
        self._tags = value

    @property
    def routing_tags(self):
        return self._routing_tags

    @routing_tags.setter
    def routing_tags(self, value):
        self._routing_tags = value

    @property
    def dynamodb_table_name(self):
        if self._dynamodb_table_name is None:
            raise self.UndefinedValueError("dynamodb_table_name")
        return self._dynamodb_table_name

    @dynamodb_table_name.setter
    def dynamodb_table_name(self, value):
        self._dynamodb_table_name = value

    @property
    def event_bridge_rule_name(self):
        return f"event-bridge-rule-{self.lambda_name}"
