#!/bin/bash
set +xe

STEP_SCRIPT_PATH=$1
STEP_SCRIPT_CONFIGURATION_FILE_PATH=$2
STEP_SCRIPT_FINISH_STATUS_FILE=$3
STEP_SCRIPT_OUTPUT_FILE_PATH=$4


if [ ! -f ${STEP_SCRIPT_CONFIGURATION_FILE_PATH} ]
then
  echo "ERROR: FILE '${STEP_SCRIPT_CONFIGURATION_FILE_PATH}' DOES NOT EXIST" >> ${STEP_SCRIPT_OUTPUT_FILE_PATH}
  echo -n "FAILURE" > ${STEP_SCRIPT_FINISH_STATUS_FILE}
fi

if [ ! -f ${STEP_SCRIPT_PATH} ]
then
  echo "ERROR: FILE '${STEP_SCRIPT_PATH}' DOES NOT EXIST" >> ${STEP_SCRIPT_OUTPUT_FILE_PATH}
  echo -n "FAILURE" > ${STEP_SCRIPT_FINISH_STATUS_FILE}
fi


${STEP_SCRIPT_PATH} --configuration-file-path ${STEP_SCRIPT_CONFIGURATION_FILE_PATH} >> ${STEP_SCRIPT_OUTPUT_FILE_PATH} 2>&1
ret=$?

if [ ${ret} != 0 ]
then
  echo "ERROR: ${STEP_SCRIPT_PATH} --configuration-file-path ${STEP_SCRIPT_CONFIGURATION_FILE_PATH} finished with ${ret}" >> ${STEP_SCRIPT_OUTPUT_FILE_PATH}
  echo -n "FAILURE" > ${STEP_SCRIPT_FINISH_STATUS_FILE}
  exit 1;
else
  echo "FINISHED: ${STEP_SCRIPT_PATH} --configuration-file-path ${STEP_SCRIPT_CONFIGURATION_FILE_PATH}" >> ${STEP_SCRIPT_OUTPUT_FILE_PATH}
  echo -n "SUCCESS" > ${STEP_SCRIPT_FINISH_STATUS_FILE}
  exit 0;
fi
